#!/bin/bash

if [ $# -ne 2 ]; then
	echo "Usage: $0 target source" >&2
	exit 1
fi

/usr/libexec/dtk5/DCore/bin/dci --export $1 $2
filename=$(basename "$2" ".dci")
echo "filename: ${filename}"

dciDir=$1/${filename}
echo "dciDir: ${dciDir}"

for sizeFolder in ${dciDir}/*; do
	size=$(basename ${sizeFolder})
	for state in normal disabled hover pressed checked; do
		if [ -d ${sizeFolder}/${state}.light/ ]; then
			for scaleFolder in ${sizeFolder}/${state}.light/*; do
				scale=$(basename ${scaleFolder})
				for file in ${scaleFolder}/*; do
					webpName=$(basename "$file" .webp)
					bl=${#webpName}
					tmp=$(echo "$webpName" | sed "s/.//g")
					al=${#tmp}
					dot=$(expr $bl - $al)
					if [ "$dot" == "1" ]; then
						mv ${scaleFolder}/{${webpName}.webp,${webpName}.0.webp}
						if [ -L ${sizeFolder}/${state}.dark/${scale}/${webpName}.webp ]; then
							rm ${sizeFolder}/${state}.dark/${scale}/${webpName}.webp
						fi
						# ln -sf
						cd ${scaleFolder}
						echo "1111111 $(pwd)"
						ln -sf ../../${state}.light/${scale}/${webpName}.0.webp ../../${state}.dark/${scale}/${webpName}.0.webp
					fi
				done
			done
		fi
	done
done

# create dci
targetFile=$1/${filename}.dci
if [ -e ${targetFile} ]; then
	rm $1/${filename}.dci
fi
/usr/libexec/dtk5/DCore/bin/dci --create $1 $1/${filename}
